name: (disabled) Status cache

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: No-op
        run: echo "Status/players feature removed. Workflow disabled."
